### ISSUE TITLE
openai.error.InvalidRequestError: That model does not exist

### ISSUE THREAD

**Issue by zzc8081** [swordintent/chatgpt-web-api#2]
127.0.0.1 - - [10/Feb/2023 10:49:43] "POST /chat HTTP/1.1" 500 -
Traceback (most recent call last):
  File "E:\tools\python\lib\site-packages\flask\app.py", line 2095, in __call__
    return self.wsgi_app(environ, start_response)
  File "E:\tools\python\lib\site-packages\flask\app.py", line 2080, in wsgi_app
    response = self.handle_exception(e)
  File "E:\tools\python\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "E:\tools\python\lib\site-packages\flask\app.py", line 2077, in wsgi_app
    response = self.full_dispatch_request()
  File "E:\tools\python\lib\site-packages\flask\app.py", line 1525, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "E:\tools\python\lib\site-packages\flask_restful\__init__.py", line 271, in error_router
    return original_handler(e)
  File "E:\tools\python\lib\site-packages\flask\app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "E:\tools\python\lib\site-packages\flask\app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "E:\tools\python\lib\site-packages\flask_restful\__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "E:\tools\python\lib\site-packages\flask\views.py", line 84, in view
    return current_app.ensure_sync(self.dispatch_request)(*args, **kwargs)
  File "E:\tools\python\lib\site-packages\flask_restful\__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "E:\project\chatgpt-web-api\src\main\resources\server.py", line 36, in post
    result = chatbot.ask(prompt)
  File "E:\tools\python\lib\site-packages\revChatGPT\Official.py", line 139, in ask
    completion = self._get_completion(
  File "E:\tools\python\lib\site-packages\revChatGPT\Official.py", line 64, in _get_completion
    return openai.Completion.create(
  File "E:\tools\python\lib\site-packages\openai\api_resources\completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "E:\tools\python\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "E:\tools\python\lib\site-packages\openai\api_requestor.py", line 226, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "E:\tools\python\lib\site-packages\openai\api_requestor.py", line 619, in _interpret_response
    self._interpret_response_line(
  File "E:\tools\python\lib\site-packages\openai\api_requestor.py", line 679, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: That model does not exist

**Comment by liuhe36** [comment]
https://github.com/swordintent/chatgpt-web-api/issues/3
